### ISSUE TITLE
Weapon classes

### ISSUE THREAD

**Issue by krlmrr** [karlm-dev/humans-vs-ai#37]
Fire, Ice, Earth, Air —- just like the good old days

**Comment by JaqueLB** [comment]
Hello! I want to know more about this feature, and maybe try to submit a PR.

Do you want to make these weapons to function as extra options for attacking, for example, showing in the battle:

Attack
Special Attack
Fire Attack
Earth Attack..

If so, how each type would affect the AI, how much attack points each one should represent?

**Comment by karlm89** [comment]
That is a great question — we haven’t really built any weapons yet — coming soon.
